apiVersion: v1
kind: Pod
metadata:
  name: ubuntu
spec:
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: cloud.google.com/gke-tpu-accelerator
            operator: In
            values:
            - tpu-v6e-slice
  tolerations:
  - operator: "Exists"
    effect: "NoExecute"
  - operator: "Exists"
    effect: "NoSchedule"
  containers:
    - name: ubuntu
      image: ubuntu:latest
      imagePullPolicy: Always
      ports:
        - name: http
          containerPort: 80
          protocol: TCP
      resources:
        {}
      command: ["/bin/bash"]
      args: ["-c", "while true; do echo hello; sleep 10;done"]
