apiVersion: v1
kind: Pod
metadata:
  name: ubuntu
spec:
  containers:
  containers:
    - name: ubuntu
      image: ubuntu:latest
      imagePullPolicy: Always
      ports:
        - name: http
          containerPort: 80
          protocol: TCP
      resources:
        {}
      command: ["/bin/bash"]
      args: ["-c", "while true; do echo hello; sleep 10;done"]
